<?
 /**
 * SplashLab Social - Facebook Open Graph Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Splashlab
 * @package     Splashlab_Fbopengraph
 * @copyright   Copyright (c) 2011 Evan Johnson / SplashLab Social (http://splashlabsocial.com)
 * @author      Evan Johnson / SplashLab Social (http://splashlabsocial.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 /*
  *  The JavaScript fbLoginCallback() function is declared in fbopengraph/fbinit.phtml
  */
?>

<?php if (Mage::helper('fbopengraph')->getAppConfig('fb_application_id')): ?>


<span >
    <fb:login-button show-faces="false" max-rows="0" perms="<?php echo Mage::helper('fbopengraph')->getAppConfig('fb_application_perms') ?>">
        <?php echo $this->__('Connect with Facebook') ?>
    </fb:login-button>
</span>


<?php endif; ?>
