<?php/**
 * SplashLab Social - Facebook Open Graph Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Splashlab
 * @package     Splashlab_Fbopengraph
 * @copyright   Copyright (c) 2011 Evan Johnson / SplashLab Social (http://splashlabsocial.com)
 * @author      Evan Johnson / SplashLab Social (http://splashlabsocial.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($appId = Mage::helper('fbopengraph')->getAppConfig('fb_application_id')): ?>
    <meta property="fb:app_id" content="<?php echo $appId ?>"/>
<?php endif; ?>
<meta property="og:site_name" content="<?php echo $this->getSiteTitle() ?>"/>
<meta property="og:title" content="<?php echo $this->getTitle() ?>"/>
<meta property="og:type" content="<?php echo $this->getType() ?>"/>
<meta property="og:image" content="<?php echo $this->getImage() ?>"/>
<meta property="og:url" content="<?php echo $this->getPageUrl() ?>"/>
<meta property="og:description" content="<?php echo $this->getDescription() ?>"/>

